name: bump
on:
  schedule:
    # run every midnight gmt
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  test:
    runs-on: macos-26
    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: false

      - name: Install homebrew
        id: homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache gems
        uses: actions/cache@v5.0.3
        with:
          path: ${{ steps.homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-test-gems-${{ steps.homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-test-gems-

      - name: Install gems
        run: brew install-bundler-gems --groups style

      - name: Hack tests
        run: |
          set -eux
          brew install gnu-sed
          cd "$(brew --repo "${GITHUB_REPOSITORY}")"
          # Work around rubocop checks cannot be suppressed
          gsed -i 's/desc ".*"/desc "Mostly harmless"/' Casks/vpinfe*.rb

      - name: Check style
        run: brew style "${GITHUB_REPOSITORY}"

  bump:
    runs-on: macos-26
    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: false

      - name: Install homebrew
        id: homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache gems
        uses: actions/cache@v5.0.3
        with:
          path: ${{ steps.homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-bump-gems-${{ steps.homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-bump-gems-

      - name: Bump versions
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/bump.sh
